/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package converter;

import java.util.ArrayList;
import jdk.nashorn.internal.objects.NativeString;

/**
 *
 * @author proxz
 */
public class ConvertGUI extends javax.swing.JFrame {

    /**
     * Creates new form ConvertGUI
     */
    public ConvertGUI() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
    }
    
    private void ConvertFilterLEO(String str) {
        
        ArrayList<String> arr = new ArrayList<>();
        
        str = str.toLowerCase().trim();
        
        str = str.replaceAll("[!?():;'`,]", "");
        String[] mass = str.split("\\P{L}+");
        //String[] mass = str.split("[\\p{L}\\p{N}_.-]*");
        
        String[] newMass = new String[mass.length - mass.length / 3];
        int j = 0;
        
        for (int i = 0; i != mass.length; i++) {
            if ((i + 1) % 3 != 0) {
                newMass[j++] = mass[i];
            }
        }
        
        for (String s: newMass){
            System.out.println(s);
        }
        
        String line = "";
        for (int i = 1; i < newMass.length; i++) {
            
            if ((i % 2) == 0) {
                line += ":" + newMass[i];
                //System.out.println(line);
                arr.add(line);
                line = "";
            } else {
            
            line += newMass[i];
            }
            
            //System.out.println("mass length: " + newMass.length + ", mass[" + i + "] = " + newMass[i]);
        }
        
        writeFinalText(arr);
        
    }
    
    private void writeFinalText(ArrayList<String> arr) {
        
        jTextArea2.setText("");
        
        for (int i = 0; i < arr.size(); i++) {
            
            jTextArea2.append(arr.get(i) + "\n");
            
        }  
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jButton1.setText("GO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(139, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jButton1)
                .addGap(16, 16, 16)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String setStr = jTextArea1.getText();
        
        ConvertFilterLEO(setStr);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
